### ISSUE TITLE
Support to release a specific version/tag/commit of SUMA

### ISSUE THREAD

**Issue by srbarrios** [moio/sumaform#502]
We want to be able to always run exactly the same version of SUMA, but 3.2-released is updated periodically including latest MUs. So we need to add support to select a specific version. Ideally that specific version of SUMA should be easier to map with a specific commit in SUMA repo.

This would mean we have to pass the version down to the installation of the pattern - hopefully then RPM will do the rest. 

https://github.com/moio/sumaform/blob/master/salt/suse_manager_server/init.sls#L18-L25 <- use a specific version instead of pkg.latest

**Comment by srbarrios** [comment]
I did some research on it, by adding a parameter to salt, so we install an specific version of the pattern:

```
suse_manager_packages:
  pkg.installed:
    - pkgs:
        {% if grains['osfullname'] == 'Leap' %}
        - patterns-uyuni_server-{{ grains.get('suma_version', '') }}
        {% else %}
        - patterns-suma_server-{{ grains.get('suma_version', '') }}
        {% endif %}
    - require:
      - sls: repos
      - sls: suse_manager_server.firewall
```

But then discussing it with @mcalmer, it will not work as the pattern doesn't specify the versions for each dependency, so we can't assure we'll allways have the version of SUMA we need, we could do it for GA, disabling Update repo, but we'll not be able to use 3.2.6 for instance.

We can specify in salt all the version of the packages contained in the pattern, but even that will not prevent to have transitive dependencies updated without control.

So, I will close it as won't fix.

We will support it internally, using our test-runner by deploying an image of SLE12SP4 with a SUMA version installed and SUMA repos disabled.
